package com.fincagis.app.presentation.main.map

import com.fincagis.app.data.local.entity.MapPointEntity
import com.fincagis.app.data.local.entity.PolygonEntity
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import com.fincagis.app.data.local.entity.PolylineEntity

fun formatCoordinate(value: Double): String {
    return String.format("%.6f", value)
}

fun formatPointDescription(description: String?): String {
    val text = description?.trim().orEmpty()
    return if (text.isBlank()) "Sin descripción" else text
}

fun formatTimestamp(timestamp: Long): String {
    val formatter = SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.getDefault())
    return formatter.format(Date(timestamp))
}

fun buildNextPointName(
    category: String,
    existingPoints: List<MapPointEntity>
): String {
    val nextIndex = existingPoints.count { it.category == category } + 1
    return "$category $nextIndex"
}

fun buildAutoNameForEditedPoint(
    category: String,
    existingPoints: List<MapPointEntity>,
    currentPointId: String
): String {
    val nextIndex = existingPoints.count {
        it.category == category && it.id != currentPointId
    } + 1

    return "$category $nextIndex"
}

fun isAutoGeneratedPointName(
    name: String,
    categories: List<String>
): Boolean {
    val trimmedName = name.trim()

    return categories.any { category ->
        trimmedName.matches(Regex("^${Regex.escape(category)}\\s+\\d+$"))
    }
}

fun buildNextPolygonName(
    existingPolygons: List<PolygonEntity>
): String {
    return "Polígono ${existingPolygons.size + 1}"
}

fun buildNextPolylineName(
    existingPolylines: List<PolylineEntity>
): String {
    return "Línea ${existingPolylines.size + 1}"
}